# Generated by Django 2.2 on 2019-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KNSVNHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=512, verbose_name='商品名稱')),
                ('itemspec', models.CharField(max_length=512, verbose_name='商品規格')),
                ('safty_stock', models.CharField(max_length=512, verbose_name='庫存安全量')),
                ('sell_platform', models.CharField(max_length=512, verbose_name='販售平台')),
                ('sum_import', models.CharField(max_length=512, verbose_name='總入庫數量')),
                ('sum_output', models.CharField(max_length=512, verbose_name='總出庫數量')),
                ('stock', models.CharField(max_length=512, verbose_name='現存數量')),
                ('remark', models.CharField(max_length=512, verbose_name='備註')),
                ('already1', models.CharField(max_length=512, verbose_name='以訂貨1')),
                ('already2', models.CharField(max_length=512, verbose_name='以訂貨2')),
                ('already3', models.CharField(max_length=512, verbose_name='以訂貨3')),
            ],
        ),
    ]
