# Generated by Django 2.2 on 2019-04-24 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_importfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KNSVNHistory',
            new_name='stock',
        ),
    ]
