# Generated by Django 2.2 on 2019-04-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190424_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'itemname', 'verbose_name_plural': 'itemnames'},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='already1',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='already2',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='already3',
        ),
        migrations.AddField(
            model_name='stock',
            name='order',
            field=models.CharField(default=0, max_length=512, verbose_name='以訂貨'),
            preserve_default=False,
        ),
    ]
