# Generated by Django 2.2 on 2019-04-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190424_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='order',
            new_name='orderss',
        ),
    ]
