# Generated by Django 2.2 on 2019-04-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190424_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='orderss',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='remark',
        ),
        migrations.AlterField(
            model_name='stock',
            name='safty_stock',
            field=models.IntegerField(blank=True, max_length=512, verbose_name='庫存安全量'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_platform',
            field=models.CharField(blank=True, max_length=512, verbose_name='販售平台'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock',
            field=models.IntegerField(blank=True, max_length=512, verbose_name='現存數量'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sum_import',
            field=models.IntegerField(blank=True, max_length=512, verbose_name='總入庫數量'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sum_output',
            field=models.IntegerField(blank=True, max_length=512, verbose_name='總出庫數量'),
        ),
    ]
