# Generated by Django 2.2 on 2019-04-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190424_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='safty_stock',
            field=models.IntegerField(max_length=512, verbose_name='庫存安全量'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_platform',
            field=models.CharField(max_length=512, verbose_name='販售平台'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock',
            field=models.IntegerField(max_length=512, verbose_name='現存數量'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sum_import',
            field=models.IntegerField(max_length=512, verbose_name='總入庫數量'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sum_output',
            field=models.IntegerField(max_length=512, verbose_name='總出庫數量'),
        ),
    ]
