# Generated by Django 2.2 on 2019-04-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190425_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('itemname', 'itemspec'), 'verbose_name': 'itemname', 'verbose_name_plural': 'itemnames'},
        ),
    ]
